version: '3'

services:
  web-server:
    build: .
    env_file: .env
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    volumes:
      - .:/app
    tty: true
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null 
